name: Copy Static Files

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder and copy files
        run: |
          mkdir -p .dist
          cp -r plugins .dist/
          echo '[{"id": "tokinovel", "name": "Toki Novel", "version": "1.0.0", "icon": "https://raw.githubusercontent.com/github/explore/main/topics/javascript/javascript.png", "site": "https://toki31.com", "lang": "all", "path": "tokinovel"}]' > .dist/plugins.min.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: .dist/
